In [ ]:
!pip install transformers torch einops
!pip install 'numpy<2'
!pip install FlashAttention --no-build-isolation

In [ ]:
from transformers import AutoModel

# Initialize the model
model = AutoModel.from_pretrained("jinaai/jina-embeddings-v3", trust_remote_code= True, use_flash_attn= False)

In [21]:
texts = [
    "Ayer tuve mucha fiebre", 
    "Hoy día me siento acalorado",
    "Gato",  
    "Piedra",  
    "Humano",  
]

# When calling the `encode` function, you can choose a `task` based on the use case:
# 'retrieval.query', 'retrieval.passage', 'separation', 'classification', 'text-matching'
# Alternatively, you can choose not to pass a `task`, and no specific LoRA adapter will be used.

#embeddings = model.encode(texts, task="text-matching")
#for emb in embeddings:
#    display(emb)
    
# Compute similarities
for i, emb in enumerate(embeddings):
    print(f'{texts[0]} - {texts[i]} = {embeddings[0] @ embeddings[i].T}')

Encoding:   0%|          | 0/1 [00:00<?, ?it/s]

array([ 0.06289606, -0.01792214, -0.10935717, ...,  0.02254054,
       -0.01256243, -0.00213539], dtype=float32)

array([ 0.09735583, -0.07901599, -0.11109967, ..., -0.00131403,
       -0.01517767, -0.02390808], dtype=float32)

array([-0.02380676, -0.10585038,  0.06259146, ..., -0.01280361,
       -0.03895217,  0.00518007], dtype=float32)

array([ 0.08454663, -0.08724174,  0.08474626, ...,  0.03209179,
       -0.01713142,  0.02260275], dtype=float32)

array([ 0.00858048, -0.14111798,  0.09575862, ..., -0.01517648,
       -0.02255368,  0.03744666], dtype=float32)

Ayer tuve mucha fiebre - Ayer tuve mucha fiebre = 1.000000238418579
Ayer tuve mucha fiebre - Hoy día me siento acalorado = 0.6129133105278015
Ayer tuve mucha fiebre - Gato = 0.10357251018285751
Ayer tuve mucha fiebre - Piedra = 0.1428723931312561
Ayer tuve mucha fiebre - Humano = 0.124265655875206
